// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eVideoPrime.Core.Entities
{
    public partial class Plan
    {
        public Plan()
        {
            PaymentDetails = new HashSet<PaymentDetail>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Currency { get; set; }

        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
}