// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eVideoPrime.Core.Entities
{
    public partial class Subscription
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public DateTime SubscribedOn { get; set; }
        public DateTime ExpiryOn { get; set; }
        public int PlanId { get; set; }

        public virtual User User { get; set; }
    }
}